### PR TITLE
Optimize encode method

### PR DESCRIPTION
**Pull request by Grinnz**
By unrolling the recursion for multi-bulk messages into a loop that processes a stack, and using an if/elsif dispatch instead of sub calls with overhead, this more than doubles the performance of ->encode with large arrays in my rudimentary tests.

### CODE REVIEW

**Comment by Grinnz** [comment]
@und3f have you gotten a chance to review these optimizations? If you would rather not have the whole internals refactored, I am willing to release this and #8 as a new alternative implementation to have the faster pureperl option available, but it would also be nice if existing users of this module benefited.

**Comment by Grinnz** [comment]
FYI, these have been released as [Protocol::Redis::Faster](https://metacpan.org/pod/Protocol::Redis::Faster) for now.

**Comment by und3f** [comment]
Please excuse the ignorant, I've had some issues. 
Just started reviewing this pull request. Actually it is great that you've created the P:R:F, it is a great idea.
Found that this code gives 7% encoding improvement!

**Comment by und3f** [comment]
Done, also I've added some more optimization, so the total encode() optimization is around 11%!

**Comment by und3f** [comment]
I see you added some nice optimizations to the P:R:Faster, will also check them.

**Pull request merged**
